---
title: "03_augment"
format: html
---

Calculating the Age from date of birth

Birth date reformat - input a date in string format, with "/" as spacer. Date format should be in MM/DD/YY

```{r}
reformat_pheno_birth_dates <- function(date_char){
  date_split <- str_split_fixed(date_char, "/", n=3)
  
  # year takes the last two characters and combines them with 19, despite its length
  year <- str_c("19", substr(date_split[,3], 
                             nchar(date_split[,3])-1,
                             nchar(date_split[,3])))
  # Month is the first element in the date_split matrix
  month <- date_split[,1]
  # Day is the second element in the date_split matrix
  day <- date_split[,2]
  # Combining the String to a date format this time in DD/MM/YY
  date_str_out <- str_c(day, "-", month, "-", year)
  # Returns as a Date.charactor in the format YY/MM/DD
  return (as.Date.character(date_str_out, "%d-%m-%Y"))
}
```

Making the age variable from the date of birth and the submission date for the article, to estimate the age. at the time of sampling.

```{r}
# first line can be ommited when name of column is birthdate from clean02
finaldata <- finaldata |> 
  mutate(birth_date = reformat_pheno_birth_dates(birth_date)) |> 
  mutate(procedure_date = as.Date.character(procedure_date, "%m/%d/%Y")) |> 
  mutate(Age = round(as.numeric(difftime(procedure_date, birth_date, units = "days")) / 365.25, 0)) |> 
   mutate(age_group = case_when(
    20 <= Age & Age < 30 ~ "(20,30]",
    30 <= Age & Age < 40 ~ "(30,40]",
    40 <= Age & Age < 50 ~ "(40,50]",
    50 <= Age & Age < 60 ~ "(50,60]",
    60 <= Age & Age < 70 ~ "(60,70]",
    70 <= Age & Age < 80 ~ "(70,80]"
  ))
  
  
# Needs to be updated maybe just replace the birth_date with age variable
# not to only select two columns
```
